-- =============================================================================
-- Migration 004: Ambassador and referral tables
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Ambassadors
-- Community members who refer seniors to Pathway.
-- referral_code is auto-generated by trigger if not provided.
-- Activation bonus ($20) triggers only after first completed Navigator session.
-- Monthly retention bonus ($10/mo) for up to 6 months.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ambassadors (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT        NOT NULL,
  phone            TEXT        NOT NULL,
  email            TEXT,
  referral_code    TEXT        NOT NULL,
  county           TEXT,
  total_referrals  INT         NOT NULL DEFAULT 0,
  active_referrals INT         NOT NULL DEFAULT 0,
  total_earned     NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  stripe_payout_id TEXT,
  active           BOOLEAN     NOT NULL DEFAULT TRUE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ambassadors_phone_unique   UNIQUE (phone),
  CONSTRAINT ambassadors_code_unique    UNIQUE (referral_code)
);

COMMENT ON TABLE ambassadors IS
  'Community ambassadors who refer seniors. '
  '$20 activation bonus (after first Navigator session) + '
  '$10/mo retention for up to 6 months per active senior.';

ALTER TABLE ambassadors ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------------------------
-- Referrals
-- Tracks ambassador-to-client referral relationships and bonus payouts.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS referrals (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  ambassador_id    UUID        NOT NULL REFERENCES ambassadors(id) ON DELETE RESTRICT,
  client_id        UUID        NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
  activated_at     TIMESTAMPTZ,
  months_paid      INT         NOT NULL DEFAULT 0 CHECK (months_paid >= 0 AND months_paid <= 6),
  total_bonus_paid NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT referrals_unique UNIQUE (ambassador_id, client_id)
);

COMMENT ON TABLE referrals IS
  'Tracks referral relationships. activated_at is set when the first Navigator '
  'session is completed (triggers the $20 activation bonus). '
  'Months_paid tracks monthly retention bonuses (max 6).';

ALTER TABLE referrals ENABLE ROW LEVEL SECURITY;
